variant = "loose"

[[issues]]
file = "src/Renderer/JsonErrorRenderer.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `InvalidArgumentException` in `Waffle\Commons\ErrorHandler\Renderer\JsonErrorRenderer::render`.'
count = 1

[[issues]]
file = "src/Renderer/JsonErrorRenderer.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `RuntimeException` in `Waffle\Commons\ErrorHandler\Renderer\JsonErrorRenderer::render`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererCoverageTest.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererCoverageTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererCoverageTest::testGetTitleForStatus`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererCoverageTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\ExpectationFailedException` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererCoverageTest::testGetTitleForStatus`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererCoverageTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererCoverageTest::testGetTitleForStatus`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererCoverageTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererCoverageTest::testGetTitleForStatus`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererCoverageTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `ReflectionException` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererCoverageTest::testGetTitleForStatus`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "mixed-argument"
message = "Invalid argument type for argument #1 of `json_decode`: expected `string`, but found `mixed`."
count = 2

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "mixed-argument"
message = "Invalid argument type for argument #1 of `strlen`: expected `string`, but found `mixed`."
count = 2

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #2 of `phpunit\framework\assert::assertarrayhaskey`: expected `ArrayAccess<array-key, mixed>|array<array-key, mixed>`, but found `mixed`.'
count = 3

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #2 of `phpunit\framework\assert::assertarraynothaskey`: expected `ArrayAccess<array-key, mixed>|array<array-key, mixed>`, but found `mixed`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "mixed-array-access"
message = "Unsafe array access on type `mixed`."
count = 2

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 2

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererTest::testRenderFormatsRfc7807Json`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererTest::testRenderHandlesInvalidArgumentException`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererTest::testRenderHandlesRouteNotFoundException`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererTest::testRenderIncludesTraceInDebugMode`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererTest::testRenderMasksUseInternalErrorInProdMode`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererTest::testRenderFormatsRfc7807Json`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererTest::testRenderHandlesInvalidArgumentException`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererTest::testRenderHandlesRouteNotFoundException`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererTest::testRenderIncludesTraceInDebugMode`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererTest::testRenderMasksUseInternalErrorInProdMode`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererTest::testRenderFormatsRfc7807Json`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererTest::testRenderHandlesInvalidArgumentException`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererTest::testRenderHandlesRouteNotFoundException`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererTest::testRenderIncludesTraceInDebugMode`.'
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `WaffleTests\Commons\ErrorHandler\JsonErrorRendererTest::testRenderMasksUseInternalErrorInProdMode`.'
count = 1

[[issues]]
file = "tests/src/Middleware/ErrorHandlerMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `WaffleTests\Commons\ErrorHandler\Middleware\ErrorHandlerMiddlewareTest::testProcessCatchesExceptionAndDelegatesToRenderer`.'
count = 1

[[issues]]
file = "tests/src/Middleware/ErrorHandlerMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Event\NoPreviousThrowableException` in `WaffleTests\Commons\ErrorHandler\Middleware\ErrorHandlerMiddlewareTest::testProcessReturnsResponseFromHandlerOnSuccess`.'
count = 1

[[issues]]
file = "tests/src/Middleware/ErrorHandlerMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\ExpectationFailedException` in `WaffleTests\Commons\ErrorHandler\Middleware\ErrorHandlerMiddlewareTest::testProcessCatchesExceptionAndDelegatesToRenderer`.'
count = 1

[[issues]]
file = "tests/src/Middleware/ErrorHandlerMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\ExpectationFailedException` in `WaffleTests\Commons\ErrorHandler\Middleware\ErrorHandlerMiddlewareTest::testProcessReturnsResponseFromHandlerOnSuccess`.'
count = 1

[[issues]]
file = "tests/src/Middleware/ErrorHandlerMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `WaffleTests\Commons\ErrorHandler\Middleware\ErrorHandlerMiddlewareTest::testProcessCatchesExceptionAndDelegatesToRenderer`.'
count = 1

[[issues]]
file = "tests/src/Middleware/ErrorHandlerMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\InvalidArgumentException` in `WaffleTests\Commons\ErrorHandler\Middleware\ErrorHandlerMiddlewareTest::testProcessReturnsResponseFromHandlerOnSuccess`.'
count = 1

[[issues]]
file = "tests/src/Middleware/ErrorHandlerMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `WaffleTests\Commons\ErrorHandler\Middleware\ErrorHandlerMiddlewareTest::testProcessCatchesExceptionAndDelegatesToRenderer`.'
count = 1

[[issues]]
file = "tests/src/Middleware/ErrorHandlerMiddlewareTest.php"
code = "unhandled-thrown-type"
message = 'Potentially unhandled exception `PHPUnit\Framework\MockObject\Exception` in `WaffleTests\Commons\ErrorHandler\Middleware\ErrorHandlerMiddlewareTest::testProcessReturnsResponseFromHandlerOnSuccess`.'
count = 1
