variant = "loose"

[[issues]]
file = "src/Renderer/JsonErrorRenderer.php"
code = "no-else-clause"
message = "Avoid `else` clauses."
count = 1

[[issues]]
file = "tests/src/AbstractTestCase.php"
code = "no-redundant-method-override"
message = "Redundant method override."
count = 2

[[issues]]
file = "tests/src/JsonErrorRendererCoverageTest.php"
code = "assertion-style"
message = "Inconsistent assertions style."
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererCoverageTest.php"
code = "no-redundant-use"
message = "Unused import: `ResponseInterface`."
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererCoverageTest.php"
code = "no-redundant-use"
message = "Unused import: `RuntimeException`."
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererCoverageTest.php"
code = "no-redundant-use"
message = "Unused import: `ServerRequestInterface`."
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererCoverageTest.php"
code = "no-redundant-use"
message = "Unused import: `StreamInterface`."
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererCoverageTest.php"
code = "no-redundant-use"
message = "Unused import: `UriInterface`."
count = 1

[[issues]]
file = "tests/src/JsonErrorRendererTest.php"
code = "literal-named-argument"
message = "Literal argument `true` should be passed as a named argument for clarity."
count = 2
